/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TSideBar: typeof import('tdesign-mobile-vue')['SideBar']
    TSideBarItem: typeof import('tdesign-mobile-vue')['SideBarItem']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
  }
}
