CREATE DATABASE IF NOT EXISTS `tg-shop` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

USE `tg-shop`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户 ID',
  `tid` VARCHAR(20) NOT NULL COMMENT '用户 Telegram ID',
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `shop` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '店铺 ID',
  `name` VARCHAR(128) NOT NULL COMMENT '店铺名称',
  `hours` VARCHAR(64) NOT NULL COMMENT '营业时间',
  `phone` VARCHAR(16) NOT NULL COMMENT '联系电话',
  `address` VARCHAR(255) NOT NULL COMMENT '地址',
  `status` INT NOT NULL COMMENT '店铺状态 0.营业中 1.休息中 2.已打烊',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) COMMENT='店铺表';

CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '分类 ID',
  `name` VARCHAR(255) NOT NULL COMMENT '分类名称',
  `shop_id` INT NOT NULL COMMENT '店铺 ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  FOREIGN KEY (shop_id) REFERENCES `shop`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='分类表';

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '商品 ID',
  `shop_id` INT NOT NULL COMMENT '店铺 ID',
  `name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `category_id` INT NOT NULL COMMENT '分类 ID',
  `price` DECIMAL(10, 2) NOT NULL COMMENT '价格',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  FOREIGN KEY (category_id) REFERENCES `categories`(`id`),
  FOREIGN KEY (shop_id) REFERENCES `shop`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='商品表';

CREATE TABLE IF NOT EXISTS `product-spec`(
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '商品规格 ID',
    `name` VARCHAR(255) NOT NULL COMMENT '规格名称',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) COMMENT='商品规格表';

CREATE TABLE IF NOT EXISTS `product-spec-values`(
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '商品规格值 ID',
    `spec_id` INT NOT NULL COMMENT '规格 ID',
    `value` VARCHAR(255) NOT NULL COMMENT '规格值',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
    FOREIGN KEY (spec_id) REFERENCES `product-spec`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='商品规格值表';

CREATE TABLE IF NOT EXISTS `product-sku`(
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '商品 SKU ID',
    `product_id` INT NOT NULL COMMENT '商品 ID',
    `sku_code` VARCHAR(255) NOT NULL COMMENT 'SKU 编码',
    `price` DECIMAL(10, 2) NOT NULL COMMENT '价格',
    `stock` INT NOT NULL COMMENT '库存',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
    FOREIGN KEY (product_id) REFERENCES `products`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='商品 SKU 表';

CREATE TABLE IF NOT EXISTS `product-sku-values`(
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '商品 SKU 规格值 ID',
    `sku_id` INT NOT NULL COMMENT 'SKU ID',
    `spec_id` INT NOT NULL COMMENT '规格 ID',
    `value` VARCHAR(255) NOT NULL COMMENT '规格值',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
    FOREIGN KEY (sku_id) REFERENCES `product-sku`(`id`),
    FOREIGN KEY (spec_id) REFERENCES `product-spec`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='商品 SKU 规格值表';


CREATE TABLE IF NOT EXISTS `carts` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '购物车 ID',
  `user_id` INT NOT NULL COMMENT '用户 ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  FOREIGN KEY (user_id) REFERENCES `users`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='购物车表';

CREATE TABLE IF NOT EXISTS `cart_items` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '购物车详情 ID',
  `cart_id` INT NOT NULL COMMENT '购物车 ID',
  `sku_id` INT NOT NULL COMMENT 'SKU ID',
  `quantity` INT NOT NULL COMMENT '数量',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  FOREIGN KEY (cart_id) REFERENCES `carts`(`id`),
  FOREIGN KEY (sku_id) REFERENCES `product-sku`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='购物车详情表';

CREATE TABLE IF NOT EXISTS `orders` (
  `id` VARCHAR(20) NOT NULL COMMENT '订单 ID',
  `user_id` INT NOT NULL COMMENT '用户 ID',
  `cart_id` INT NOT NULL COMMENT '购物车 ID',
  `total` DECIMAL(10, 2) NOT NULL COMMENT '总价',
  `status` INT NOT NULL COMMENT '订单状态 0.已完成 1.处理中 2.已取消',
  `payment_id` INT NOT NULL COMMENT '支付 ID',
  `payment_status` INT NOT NULL COMMENT '支付状态 0.已支付 1.未支付 2.已退款 3.退款中',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
  FOREIGN KEY (user_id) REFERENCES `users`(`id`),
  FOREIGN KEY (cart_id) REFERENCES `carts`(`id`),
  PRIMARY KEY (`id`)
) COMMENT='订单表';
